### PR TITLE
Ampere support (RTX3000)

### PR DESCRIPTION
**Pull request by AlgirdasKartavicius**
Added CUDA 11.1 dll for ampere architecture support.

### CODE REVIEW

**Comment by honfika** [comment]
Thank you very much.

Is it working with Cuda 10.x with the extra parameter? What happens with that version in this case?

Maybe both init DllImport should be added (with and without the catchsize), and adding a config settings/flag.... or just a try - catch.. and try the other in the catch block.

**Comment by honfika** [comment]
Anyway I merge it now.... I'll check the batchSize thing in the weekend.
Thank you.

**Comment by AlgirdasKartavicius** [comment]
Yes, i am adding method to test Cuda version.

**Comment by zgabi** [comment]
Thank you very much.

Is it working with Cuda 10.x with the extra parameter? What happens with that version in this case?

Maybe both init DllImport should be added (with and without the batchsize), and adding a config settings/flag.... or just a try - catch.. and try the other in the catch block.

(I used a wrong github account some minutes ago :)

**Pull request merged**
